#!/usr/bin/env ruby

require 'bundler'
Bundler.require :default, :test, :development

require 'sinatra/base'

class Server < Sinatra::Base
  get '/:name' do
    root_directory = Pathname.new(File.expand_path('../../tmp/aruba', __FILE__))
    File.read(File.join(root_directory, params[:name]))
  end
end

Server.run!
